# Generated by Django 5.1.5 on 2025-03-12 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="contributer's first name", max_length=50)),
                ('last_name', models.CharField(help_text="contributer's last name", max_length=50)),
                ('email', models.EmailField(help_text="contributer's email address", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=50)),
                ('website', models.URLField(help_text='The Publisher website')),
                ('email', models.EmailField(help_text="Publisher's email address", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MovieContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], max_length=20, verbose_name='The role this contributor had in the movie. ')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.contributors')),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the movie', max_length=100)),
                ('date', models.DateField(verbose_name='Date of release.')),
                ('contributors', models.ManyToManyField(through='MoviesListApp.MovieContributor', to='MoviesListApp.contributors')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='moviecontributor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.movies_info'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Review text')),
                ('rating', models.IntegerField(help_text='Rating of the reviewer')),
                ('date_creating', models.DateTimeField(auto_now_add=True, help_text='date and time created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(help_text='The movie that this review is for', on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.movies_info')),
            ],
        ),
    ]
